// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: completions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCompletion = `-- name: CreateCompletion :exec
INSERT INTO completions (user_id, lesson_id)
VALUES ($1, $2)
ON CONFLICT (user_id, lesson_id) DO NOTHING
`

type CreateCompletionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	LessonID uuid.UUID `json:"lesson_id"`
}

func (q *Queries) CreateCompletion(ctx context.Context, arg CreateCompletionParams) error {
	_, err := q.db.Exec(ctx, createCompletion, arg.UserID, arg.LessonID)
	return err
}

const deleteCompletion = `-- name: DeleteCompletion :exec
DELETE FROM completions WHERE user_id = $1 AND lesson_id = $2
`

type DeleteCompletionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	LessonID uuid.UUID `json:"lesson_id"`
}

func (q *Queries) DeleteCompletion(ctx context.Context, arg DeleteCompletionParams) error {
	_, err := q.db.Exec(ctx, deleteCompletion, arg.UserID, arg.LessonID)
	return err
}

const listCompletionsByUserAndCourse = `-- name: ListCompletionsByUserAndCourse :many
SELECT c.id, c.user_id, c.lesson_id, c.completed_at
FROM completions c
JOIN lessons l ON l.id = c.lesson_id
WHERE c.user_id = $1 AND l.course_id = $2
`

type ListCompletionsByUserAndCourseParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) ListCompletionsByUserAndCourse(ctx context.Context, arg ListCompletionsByUserAndCourseParams) ([]Completion, error) {
	rows, err := q.db.Query(ctx, listCompletionsByUserAndCourse, arg.UserID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Completion
	for rows.Next() {
		var i Completion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
