// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (owner_id, title, description, tags, thumbnail_url, visibility)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
`

type CreateCourseParams struct {
	OwnerID      uuid.UUID   `json:"owner_id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	Tags         []string    `json:"tags"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
	Visibility   Visibility  `json:"visibility"`
}

type CreateCourseRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CreateCourseRow, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.ThumbnailUrl,
		arg.Visibility,
	)
	var i CreateCourseRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.ThumbnailUrl,
		&i.Visibility,
		&i.ForkedFromID,
		&i.ForkedAt,
		&i.EmbedBroken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createForkedCourse = `-- name: CreateForkedCourse :one
INSERT INTO courses (owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at)
VALUES ($1, $2, $3, $4, $5, 'private', $6, now())
RETURNING id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
`

type CreateForkedCourseParams struct {
	OwnerID      uuid.UUID   `json:"owner_id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	Tags         []string    `json:"tags"`
	ThumbnailUrl pgtype.Text `json:"thumbnail_url"`
	ForkedFromID pgtype.UUID `json:"forked_from_id"`
}

type CreateForkedCourseRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) CreateForkedCourse(ctx context.Context, arg CreateForkedCourseParams) (CreateForkedCourseRow, error) {
	row := q.db.QueryRow(ctx, createForkedCourse,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.ThumbnailUrl,
		arg.ForkedFromID,
	)
	var i CreateForkedCourseRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.ThumbnailUrl,
		&i.Visibility,
		&i.ForkedFromID,
		&i.ForkedAt,
		&i.EmbedBroken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1 AND owner_id = $2
`

type DeleteCourseParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteCourse(ctx context.Context, arg DeleteCourseParams) error {
	_, err := q.db.Exec(ctx, deleteCourse, arg.ID, arg.OwnerID)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
FROM courses
WHERE id = $1
  AND (
    visibility = 'public'
    OR visibility = 'unlisted'
    OR owner_id = $2
  )
`

type GetCourseByIDParams struct {
	ID       uuid.UUID   `json:"id"`
	ViewerID pgtype.UUID `json:"viewer_id"`
}

type GetCourseByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) GetCourseByID(ctx context.Context, arg GetCourseByIDParams) (GetCourseByIDRow, error) {
	row := q.db.QueryRow(ctx, getCourseByID, arg.ID, arg.ViewerID)
	var i GetCourseByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.ThumbnailUrl,
		&i.Visibility,
		&i.ForkedFromID,
		&i.ForkedAt,
		&i.EmbedBroken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByIDOwnerOnly = `-- name: GetCourseByIDOwnerOnly :one
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
FROM courses
WHERE id = $1 AND owner_id = $2
`

type GetCourseByIDOwnerOnlyParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type GetCourseByIDOwnerOnlyRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) GetCourseByIDOwnerOnly(ctx context.Context, arg GetCourseByIDOwnerOnlyParams) (GetCourseByIDOwnerOnlyRow, error) {
	row := q.db.QueryRow(ctx, getCourseByIDOwnerOnly, arg.ID, arg.OwnerID)
	var i GetCourseByIDOwnerOnlyRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.ThumbnailUrl,
		&i.Visibility,
		&i.ForkedFromID,
		&i.ForkedAt,
		&i.EmbedBroken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicCourses = `-- name: ListPublicCourses :many
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
FROM courses
WHERE visibility = 'public'
ORDER BY created_at DESC
LIMIT $1
`

type ListPublicCoursesRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) ListPublicCourses(ctx context.Context, limit int32) ([]ListPublicCoursesRow, error) {
	rows, err := q.db.Query(ctx, listPublicCourses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicCoursesRow
	for rows.Next() {
		var i ListPublicCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.ThumbnailUrl,
			&i.Visibility,
			&i.ForkedFromID,
			&i.ForkedAt,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCoursesCursor = `-- name: ListPublicCoursesCursor :many
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
FROM courses
WHERE visibility = 'public' AND created_at < $1
ORDER BY created_at DESC
LIMIT $2
`

type ListPublicCoursesCursorParams struct {
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

type ListPublicCoursesCursorRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) ListPublicCoursesCursor(ctx context.Context, arg ListPublicCoursesCursorParams) ([]ListPublicCoursesCursorRow, error) {
	rows, err := q.db.Query(ctx, listPublicCoursesCursor, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicCoursesCursorRow
	for rows.Next() {
		var i ListPublicCoursesCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.ThumbnailUrl,
			&i.Visibility,
			&i.ForkedFromID,
			&i.ForkedAt,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCourses = `-- name: ListUserCourses :many
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
FROM courses
WHERE owner_id = $1
  AND (
    visibility = 'public'
    OR visibility = 'unlisted'
    OR owner_id = $2
  )
ORDER BY created_at DESC
`

type ListUserCoursesParams struct {
	OwnerID  uuid.UUID   `json:"owner_id"`
	ViewerID pgtype.UUID `json:"viewer_id"`
}

type ListUserCoursesRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) ListUserCourses(ctx context.Context, arg ListUserCoursesParams) ([]ListUserCoursesRow, error) {
	rows, err := q.db.Query(ctx, listUserCourses, arg.OwnerID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCoursesRow
	for rows.Next() {
		var i ListUserCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.ThumbnailUrl,
			&i.Visibility,
			&i.ForkedFromID,
			&i.ForkedAt,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOwnCourses = `-- name: ListUserOwnCourses :many
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
FROM courses
WHERE owner_id = $1
ORDER BY created_at DESC
`

type ListUserOwnCoursesRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) ListUserOwnCourses(ctx context.Context, ownerID uuid.UUID) ([]ListUserOwnCoursesRow, error) {
	rows, err := q.db.Query(ctx, listUserOwnCourses, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOwnCoursesRow
	for rows.Next() {
		var i ListUserOwnCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.ThumbnailUrl,
			&i.Visibility,
			&i.ForkedFromID,
			&i.ForkedAt,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCourses = `-- name: SearchCourses :many
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at,
       ts_rank(search_vector, websearch_to_tsquery('english', $1)) AS rank
FROM courses
WHERE visibility = 'public'
  AND search_vector @@ websearch_to_tsquery('english', $1)
ORDER BY rank DESC, created_at DESC
LIMIT $2
`

type SearchCoursesParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Limit              int32  `json:"limit"`
}

type SearchCoursesRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	Rank         float32            `json:"rank"`
}

func (q *Queries) SearchCourses(ctx context.Context, arg SearchCoursesParams) ([]SearchCoursesRow, error) {
	rows, err := q.db.Query(ctx, searchCourses, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCoursesRow
	for rows.Next() {
		var i SearchCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.ThumbnailUrl,
			&i.Visibility,
			&i.ForkedFromID,
			&i.ForkedAt,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCoursesByTags = `-- name: SearchCoursesByTags :many
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
FROM courses
WHERE visibility = 'public'
  AND tags @> $1::text[]
ORDER BY created_at DESC
LIMIT $2
`

type SearchCoursesByTagsParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
}

type SearchCoursesByTagsRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) SearchCoursesByTags(ctx context.Context, arg SearchCoursesByTagsParams) ([]SearchCoursesByTagsRow, error) {
	rows, err := q.db.Query(ctx, searchCoursesByTags, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCoursesByTagsRow
	for rows.Next() {
		var i SearchCoursesByTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.ThumbnailUrl,
			&i.Visibility,
			&i.ForkedFromID,
			&i.ForkedAt,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCoursesCursor = `-- name: SearchCoursesCursor :many
SELECT id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at,
       ts_rank(search_vector, websearch_to_tsquery('english', $1)) AS rank
FROM courses
WHERE visibility = 'public'
  AND search_vector @@ websearch_to_tsquery('english', $1)
  AND created_at < $2
ORDER BY rank DESC, created_at DESC
LIMIT $3
`

type SearchCoursesCursorParams struct {
	WebsearchToTsquery string    `json:"websearch_to_tsquery"`
	CreatedAt          time.Time `json:"created_at"`
	Limit              int32     `json:"limit"`
}

type SearchCoursesCursorRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	Rank         float32            `json:"rank"`
}

func (q *Queries) SearchCoursesCursor(ctx context.Context, arg SearchCoursesCursorParams) ([]SearchCoursesCursorRow, error) {
	rows, err := q.db.Query(ctx, searchCoursesCursor, arg.WebsearchToTsquery, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCoursesCursorRow
	for rows.Next() {
		var i SearchCoursesCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.ThumbnailUrl,
			&i.Visibility,
			&i.ForkedFromID,
			&i.ForkedAt,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCourseEmbedBroken = `-- name: SetCourseEmbedBroken :exec
UPDATE courses SET embed_broken = $2, updated_at = now() WHERE id = $1
`

type SetCourseEmbedBrokenParams struct {
	ID          uuid.UUID `json:"id"`
	EmbedBroken bool      `json:"embed_broken"`
}

func (q *Queries) SetCourseEmbedBroken(ctx context.Context, arg SetCourseEmbedBrokenParams) error {
	_, err := q.db.Exec(ctx, setCourseEmbedBroken, arg.ID, arg.EmbedBroken)
	return err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET title = COALESCE($3, title),
    description = COALESCE($4, description),
    tags = COALESCE($5, tags),
    thumbnail_url = COALESCE($6, thumbnail_url),
    visibility = COALESCE($7, visibility),
    updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, title, description, tags, thumbnail_url, visibility, forked_from_id, forked_at, embed_broken, created_at, updated_at
`

type UpdateCourseParams struct {
	ID           uuid.UUID      `json:"id"`
	OwnerID      uuid.UUID      `json:"owner_id"`
	Title        pgtype.Text    `json:"title"`
	Description  pgtype.Text    `json:"description"`
	Tags         []string       `json:"tags"`
	ThumbnailUrl pgtype.Text    `json:"thumbnail_url"`
	Visibility   NullVisibility `json:"visibility"`
}

type UpdateCourseRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (UpdateCourseRow, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.ThumbnailUrl,
		arg.Visibility,
	)
	var i UpdateCourseRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.ThumbnailUrl,
		&i.Visibility,
		&i.ForkedFromID,
		&i.ForkedAt,
		&i.EmbedBroken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
