// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (course_id, parent_id, position, type, title)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, parent_id, position, type, title, embed_broken, created_at, updated_at
`

type CreateLessonParams struct {
	CourseID uuid.UUID   `json:"course_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Position int32       `json:"position"`
	Type     LessonType  `json:"type"`
	Title    string      `json:"title"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.CourseID,
		arg.ParentID,
		arg.Position,
		arg.Type,
		arg.Title,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ParentID,
		&i.Position,
		&i.Type,
		&i.Title,
		&i.EmbedBroken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPageLesson = `-- name: CreatePageLesson :exec
INSERT INTO page_lessons (lesson_id, content)
VALUES ($1, $2)
`

type CreatePageLessonParams struct {
	LessonID uuid.UUID `json:"lesson_id"`
	Content  []byte    `json:"content"`
}

func (q *Queries) CreatePageLesson(ctx context.Context, arg CreatePageLessonParams) error {
	_, err := q.db.Exec(ctx, createPageLesson, arg.LessonID, arg.Content)
	return err
}

const createQuizLesson = `-- name: CreateQuizLesson :exec
INSERT INTO quiz_lessons (lesson_id, questions)
VALUES ($1, $2)
`

type CreateQuizLessonParams struct {
	LessonID  uuid.UUID `json:"lesson_id"`
	Questions []byte    `json:"questions"`
}

func (q *Queries) CreateQuizLesson(ctx context.Context, arg CreateQuizLessonParams) error {
	_, err := q.db.Exec(ctx, createQuizLesson, arg.LessonID, arg.Questions)
	return err
}

const createVideoLesson = `-- name: CreateVideoLesson :exec
INSERT INTO video_lessons (lesson_id, provider, provider_id, start_seconds, end_seconds, curator_notes, source_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateVideoLessonParams struct {
	LessonID     uuid.UUID       `json:"lesson_id"`
	Provider     VideoProvider   `json:"provider"`
	ProviderID   string          `json:"provider_id"`
	StartSeconds pgtype.Int4     `json:"start_seconds"`
	EndSeconds   pgtype.Int4     `json:"end_seconds"`
	CuratorNotes json.RawMessage `json:"curator_notes"`
	SourceUrl    string          `json:"source_url"`
}

func (q *Queries) CreateVideoLesson(ctx context.Context, arg CreateVideoLessonParams) error {
	_, err := q.db.Exec(ctx, createVideoLesson,
		arg.LessonID,
		arg.Provider,
		arg.ProviderID,
		arg.StartSeconds,
		arg.EndSeconds,
		arg.CuratorNotes,
		arg.SourceUrl,
	)
	return err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons WHERE id = $1 AND course_id = $2
`

type DeleteLessonParams struct {
	ID       uuid.UUID `json:"id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) DeleteLesson(ctx context.Context, arg DeleteLessonParams) error {
	_, err := q.db.Exec(ctx, deleteLesson, arg.ID, arg.CourseID)
	return err
}

const getAllVideoLessons = `-- name: GetAllVideoLessons :many
SELECT vl.lesson_id, vl.provider, vl.provider_id, vl.start_seconds, vl.end_seconds, vl.curator_notes, vl.source_url
FROM video_lessons vl
JOIN lessons l ON l.id = vl.lesson_id
JOIN courses c ON c.id = l.course_id
WHERE c.owner_id != '00000000-0000-0000-0000-000000000001'
`

func (q *Queries) GetAllVideoLessons(ctx context.Context) ([]VideoLesson, error) {
	rows, err := q.db.Query(ctx, getAllVideoLessons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoLesson
	for rows.Next() {
		var i VideoLesson
		if err := rows.Scan(
			&i.LessonID,
			&i.Provider,
			&i.ProviderID,
			&i.StartSeconds,
			&i.EndSeconds,
			&i.CuratorNotes,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, course_id, parent_id, position, type, title, embed_broken, created_at, updated_at
FROM lessons
WHERE id = $1 AND course_id = $2
`

type GetLessonByIDParams struct {
	ID       uuid.UUID `json:"id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) GetLessonByID(ctx context.Context, arg GetLessonByIDParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByID, arg.ID, arg.CourseID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ParentID,
		&i.Position,
		&i.Type,
		&i.Title,
		&i.EmbedBroken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxPosition = `-- name: GetMaxPosition :one
SELECT COALESCE(MAX(position), -1)::integer AS max_pos
FROM lessons
WHERE course_id = $1
  AND COALESCE(parent_id, '00000000-0000-0000-0000-000000000000'::uuid) = COALESCE($2, '00000000-0000-0000-0000-000000000000'::uuid)
`

type GetMaxPositionParams struct {
	CourseID uuid.UUID   `json:"course_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetMaxPosition(ctx context.Context, arg GetMaxPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxPosition, arg.CourseID, arg.ParentID)
	var max_pos int32
	err := row.Scan(&max_pos)
	return max_pos, err
}

const getPageLesson = `-- name: GetPageLesson :one
SELECT lesson_id, content
FROM page_lessons
WHERE lesson_id = $1
`

func (q *Queries) GetPageLesson(ctx context.Context, lessonID uuid.UUID) (PageLesson, error) {
	row := q.db.QueryRow(ctx, getPageLesson, lessonID)
	var i PageLesson
	err := row.Scan(&i.LessonID, &i.Content)
	return i, err
}

const getQuizLesson = `-- name: GetQuizLesson :one
SELECT lesson_id, questions
FROM quiz_lessons
WHERE lesson_id = $1
`

func (q *Queries) GetQuizLesson(ctx context.Context, lessonID uuid.UUID) (QuizLesson, error) {
	row := q.db.QueryRow(ctx, getQuizLesson, lessonID)
	var i QuizLesson
	err := row.Scan(&i.LessonID, &i.Questions)
	return i, err
}

const getVideoLesson = `-- name: GetVideoLesson :one
SELECT lesson_id, provider, provider_id, start_seconds, end_seconds, curator_notes, source_url
FROM video_lessons
WHERE lesson_id = $1
`

func (q *Queries) GetVideoLesson(ctx context.Context, lessonID uuid.UUID) (VideoLesson, error) {
	row := q.db.QueryRow(ctx, getVideoLesson, lessonID)
	var i VideoLesson
	err := row.Scan(
		&i.LessonID,
		&i.Provider,
		&i.ProviderID,
		&i.StartSeconds,
		&i.EndSeconds,
		&i.CuratorNotes,
		&i.SourceUrl,
	)
	return i, err
}

const listLessonsByCourse = `-- name: ListLessonsByCourse :many
SELECT id, course_id, parent_id, position, type, title, embed_broken, created_at, updated_at
FROM lessons
WHERE course_id = $1
ORDER BY COALESCE(parent_id, '00000000-0000-0000-0000-000000000000'::uuid), position
`

func (q *Queries) ListLessonsByCourse(ctx context.Context, courseID uuid.UUID) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ParentID,
			&i.Position,
			&i.Type,
			&i.Title,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLessonEmbedBroken = `-- name: SetLessonEmbedBroken :exec
UPDATE lessons SET embed_broken = $2, updated_at = now() WHERE id = $1
`

type SetLessonEmbedBrokenParams struct {
	ID          uuid.UUID `json:"id"`
	EmbedBroken bool      `json:"embed_broken"`
}

func (q *Queries) SetLessonEmbedBroken(ctx context.Context, arg SetLessonEmbedBrokenParams) error {
	_, err := q.db.Exec(ctx, setLessonEmbedBroken, arg.ID, arg.EmbedBroken)
	return err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons
SET title = COALESCE($3, title),
    parent_id = COALESCE($4, parent_id),
    position = COALESCE($5, position),
    updated_at = now()
WHERE id = $1 AND course_id = $2
RETURNING id, course_id, parent_id, position, type, title, embed_broken, created_at, updated_at
`

type UpdateLessonParams struct {
	ID       uuid.UUID   `json:"id"`
	CourseID uuid.UUID   `json:"course_id"`
	Title    pgtype.Text `json:"title"`
	ParentID pgtype.UUID `json:"parent_id"`
	Position pgtype.Int4 `json:"position"`
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.ParentID,
		arg.Position,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ParentID,
		&i.Position,
		&i.Type,
		&i.Title,
		&i.EmbedBroken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLessonPosition = `-- name: UpdateLessonPosition :exec
UPDATE lessons SET parent_id = $2, position = $3, updated_at = now()
WHERE id = $1
`

type UpdateLessonPositionParams struct {
	ID       uuid.UUID   `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Position int32       `json:"position"`
}

func (q *Queries) UpdateLessonPosition(ctx context.Context, arg UpdateLessonPositionParams) error {
	_, err := q.db.Exec(ctx, updateLessonPosition, arg.ID, arg.ParentID, arg.Position)
	return err
}

const updatePageLesson = `-- name: UpdatePageLesson :exec
UPDATE page_lessons SET content = $2 WHERE lesson_id = $1
`

type UpdatePageLessonParams struct {
	LessonID uuid.UUID `json:"lesson_id"`
	Content  []byte    `json:"content"`
}

func (q *Queries) UpdatePageLesson(ctx context.Context, arg UpdatePageLessonParams) error {
	_, err := q.db.Exec(ctx, updatePageLesson, arg.LessonID, arg.Content)
	return err
}

const updateQuizLesson = `-- name: UpdateQuizLesson :exec
UPDATE quiz_lessons SET questions = $2 WHERE lesson_id = $1
`

type UpdateQuizLessonParams struct {
	LessonID  uuid.UUID `json:"lesson_id"`
	Questions []byte    `json:"questions"`
}

func (q *Queries) UpdateQuizLesson(ctx context.Context, arg UpdateQuizLessonParams) error {
	_, err := q.db.Exec(ctx, updateQuizLesson, arg.LessonID, arg.Questions)
	return err
}

const updateVideoLesson = `-- name: UpdateVideoLesson :exec
UPDATE video_lessons
SET provider_id = COALESCE($2, provider_id),
    start_seconds = $3,
    end_seconds = $4,
    curator_notes = $5,
    source_url = COALESCE($6, source_url)
WHERE lesson_id = $1
`

type UpdateVideoLessonParams struct {
	LessonID     uuid.UUID       `json:"lesson_id"`
	ProviderID   pgtype.Text     `json:"provider_id"`
	StartSeconds pgtype.Int4     `json:"start_seconds"`
	EndSeconds   pgtype.Int4     `json:"end_seconds"`
	CuratorNotes json.RawMessage `json:"curator_notes"`
	SourceUrl    pgtype.Text     `json:"source_url"`
}

func (q *Queries) UpdateVideoLesson(ctx context.Context, arg UpdateVideoLessonParams) error {
	_, err := q.db.Exec(ctx, updateVideoLesson,
		arg.LessonID,
		arg.ProviderID,
		arg.StartSeconds,
		arg.EndSeconds,
		arg.CuratorNotes,
		arg.SourceUrl,
	)
	return err
}
