// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LessonType string

const (
	LessonTypeVideo LessonType = "video"
	LessonTypePage  LessonType = "page"
	LessonTypeQuiz  LessonType = "quiz"
)

func (e *LessonType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LessonType(s)
	case string:
		*e = LessonType(s)
	default:
		return fmt.Errorf("unsupported scan type for LessonType: %T", src)
	}
	return nil
}

type NullLessonType struct {
	LessonType LessonType `json:"lesson_type"`
	Valid      bool       `json:"valid"` // Valid is true if LessonType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLessonType) Scan(value interface{}) error {
	if value == nil {
		ns.LessonType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LessonType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLessonType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LessonType), nil
}

type QuestionType string

const (
	QuestionTypeMultipleChoice QuestionType = "multiple_choice"
	QuestionTypeShortAnswer    QuestionType = "short_answer"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType `json:"question_type"`
	Valid        bool         `json:"valid"` // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

type ReportCategory string

const (
	ReportCategoryIncorrect ReportCategory = "incorrect"
	ReportCategoryHarmful   ReportCategory = "harmful"
	ReportCategoryCopyright ReportCategory = "copyright"
	ReportCategoryOther     ReportCategory = "other"
)

func (e *ReportCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportCategory(s)
	case string:
		*e = ReportCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportCategory: %T", src)
	}
	return nil
}

type NullReportCategory struct {
	ReportCategory ReportCategory `json:"report_category"`
	Valid          bool           `json:"valid"` // Valid is true if ReportCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ReportCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportCategory), nil
}

type ReportStatus string

const (
	ReportStatusOpen      ReportStatus = "open"
	ReportStatusReviewed  ReportStatus = "reviewed"
	ReportStatusActioned  ReportStatus = "actioned"
	ReportStatusDismissed ReportStatus = "dismissed"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus `json:"report_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type ReportTargetType string

const (
	ReportTargetTypeCourse ReportTargetType = "course"
	ReportTargetTypeLesson ReportTargetType = "lesson"
)

func (e *ReportTargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportTargetType(s)
	case string:
		*e = ReportTargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportTargetType: %T", src)
	}
	return nil
}

type NullReportTargetType struct {
	ReportTargetType ReportTargetType `json:"report_target_type"`
	Valid            bool             `json:"valid"` // Valid is true if ReportTargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.ReportTargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportTargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportTargetType), nil
}

type VideoProvider string

const (
	VideoProviderYoutube VideoProvider = "youtube"
)

func (e *VideoProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoProvider(s)
	case string:
		*e = VideoProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoProvider: %T", src)
	}
	return nil
}

type NullVideoProvider struct {
	VideoProvider VideoProvider `json:"video_provider"`
	Valid         bool          `json:"valid"` // Valid is true if VideoProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoProvider) Scan(value interface{}) error {
	if value == nil {
		ns.VideoProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoProvider), nil
}

type Visibility string

const (
	VisibilityPublic   Visibility = "public"
	VisibilityUnlisted Visibility = "unlisted"
	VisibilityPrivate  Visibility = "private"
)

func (e *Visibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Visibility(s)
	case string:
		*e = Visibility(s)
	default:
		return fmt.Errorf("unsupported scan type for Visibility: %T", src)
	}
	return nil
}

type NullVisibility struct {
	Visibility Visibility `json:"visibility"`
	Valid      bool       `json:"valid"` // Valid is true if Visibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.Visibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Visibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Visibility), nil
}

type Completion struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	LessonID    uuid.UUID `json:"lesson_id"`
	CompletedAt time.Time `json:"completed_at"`
}

type Course struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	SearchVector interface{}        `json:"search_vector"`
}

type Lesson struct {
	ID          uuid.UUID   `json:"id"`
	CourseID    uuid.UUID   `json:"course_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Position    int32       `json:"position"`
	Type        LessonType  `json:"type"`
	Title       string      `json:"title"`
	EmbedBroken bool        `json:"embed_broken"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type MagicLinkToken struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type OauthAccount struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type PageLesson struct {
	LessonID uuid.UUID `json:"lesson_id"`
	Content  []byte    `json:"content"`
}

type QuizAttempt struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	LessonID  uuid.UUID      `json:"lesson_id"`
	Answers   []byte         `json:"answers"`
	Score     pgtype.Numeric `json:"score"`
	CreatedAt time.Time      `json:"created_at"`
}

type QuizLesson struct {
	LessonID  uuid.UUID `json:"lesson_id"`
	Questions []byte    `json:"questions"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Report struct {
	ID         uuid.UUID          `json:"id"`
	ReporterID uuid.UUID          `json:"reporter_id"`
	TargetType ReportTargetType   `json:"target_type"`
	TargetID   uuid.UUID          `json:"target_id"`
	Category   ReportCategory     `json:"category"`
	Body       pgtype.Text        `json:"body"`
	Status     ReportStatus       `json:"status"`
	ReviewedBy pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Safe struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CourseID  uuid.UUID `json:"course_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	DisplayName         string             `json:"display_name"`
	Bio                 pgtype.Text        `json:"bio"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	IsAdmin             bool               `json:"is_admin"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletionScheduledAt pgtype.Timestamptz `json:"deletion_scheduled_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type VideoLesson struct {
	LessonID     uuid.UUID       `json:"lesson_id"`
	Provider     VideoProvider   `json:"provider"`
	ProviderID   string          `json:"provider_id"`
	StartSeconds pgtype.Int4     `json:"start_seconds"`
	EndSeconds   pgtype.Int4     `json:"end_seconds"`
	CuratorNotes json.RawMessage `json:"curator_notes"`
	SourceUrl    string          `json:"source_url"`
}
