// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_attempts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuizAttempt = `-- name: CreateQuizAttempt :one
INSERT INTO quiz_attempts (user_id, lesson_id, answers, score)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, lesson_id, answers, score, created_at
`

type CreateQuizAttemptParams struct {
	UserID   uuid.UUID      `json:"user_id"`
	LessonID uuid.UUID      `json:"lesson_id"`
	Answers  []byte         `json:"answers"`
	Score    pgtype.Numeric `json:"score"`
}

func (q *Queries) CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, createQuizAttempt,
		arg.UserID,
		arg.LessonID,
		arg.Answers,
		arg.Score,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LessonID,
		&i.Answers,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const listQuizAttemptsByUser = `-- name: ListQuizAttemptsByUser :many
SELECT id, user_id, lesson_id, answers, score, created_at
FROM quiz_attempts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListQuizAttemptsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListQuizAttemptsByUser(ctx context.Context, arg ListQuizAttemptsByUserParams) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, listQuizAttemptsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAttempt
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.Answers,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttemptsByUserAndLesson = `-- name: ListQuizAttemptsByUserAndLesson :many
SELECT id, user_id, lesson_id, answers, score, created_at
FROM quiz_attempts
WHERE user_id = $1 AND lesson_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListQuizAttemptsByUserAndLessonParams struct {
	UserID   uuid.UUID `json:"user_id"`
	LessonID uuid.UUID `json:"lesson_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListQuizAttemptsByUserAndLesson(ctx context.Context, arg ListQuizAttemptsByUserAndLessonParams) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, listQuizAttemptsByUserAndLesson, arg.UserID, arg.LessonID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAttempt
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.Answers,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttemptsByUserAndLessonCursor = `-- name: ListQuizAttemptsByUserAndLessonCursor :many
SELECT id, user_id, lesson_id, answers, score, created_at
FROM quiz_attempts
WHERE user_id = $1 AND lesson_id = $2 AND created_at < $3
ORDER BY created_at DESC
LIMIT $4
`

type ListQuizAttemptsByUserAndLessonCursorParams struct {
	UserID    uuid.UUID `json:"user_id"`
	LessonID  uuid.UUID `json:"lesson_id"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListQuizAttemptsByUserAndLessonCursor(ctx context.Context, arg ListQuizAttemptsByUserAndLessonCursorParams) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, listQuizAttemptsByUserAndLessonCursor,
		arg.UserID,
		arg.LessonID,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAttempt
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.Answers,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAttemptsByUserCursor = `-- name: ListQuizAttemptsByUserCursor :many
SELECT id, user_id, lesson_id, answers, score, created_at
FROM quiz_attempts
WHERE user_id = $1 AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ListQuizAttemptsByUserCursorParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListQuizAttemptsByUserCursor(ctx context.Context, arg ListQuizAttemptsByUserCursorParams) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, listQuizAttemptsByUserCursor, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAttempt
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.Answers,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
