// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, target_type, target_id, category, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, reporter_id, target_type, target_id, category, body, status, reviewed_by, reviewed_at, created_at
`

type CreateReportParams struct {
	ReporterID uuid.UUID        `json:"reporter_id"`
	TargetType ReportTargetType `json:"target_type"`
	TargetID   uuid.UUID        `json:"target_id"`
	Category   ReportCategory   `json:"category"`
	Body       pgtype.Text      `json:"body"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetID,
		arg.Category,
		arg.Body,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Category,
		&i.Body,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExistingReport = `-- name: GetExistingReport :one
SELECT id, reporter_id, target_type, target_id, category, body, status, reviewed_by, reviewed_at, created_at
FROM reports
WHERE reporter_id = $1 AND target_type = $2 AND target_id = $3
LIMIT 1
`

type GetExistingReportParams struct {
	ReporterID uuid.UUID        `json:"reporter_id"`
	TargetType ReportTargetType `json:"target_type"`
	TargetID   uuid.UUID        `json:"target_id"`
}

func (q *Queries) GetExistingReport(ctx context.Context, arg GetExistingReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, getExistingReport, arg.ReporterID, arg.TargetType, arg.TargetID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Category,
		&i.Body,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listReportsByStatus = `-- name: ListReportsByStatus :many
SELECT id, reporter_id, target_type, target_id, category, body, status, reviewed_by, reviewed_at, created_at
FROM reports
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListReportsByStatusParams struct {
	Status ReportStatus `json:"status"`
	Limit  int32        `json:"limit"`
}

func (q *Queries) ListReportsByStatus(ctx context.Context, arg ListReportsByStatusParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.TargetType,
			&i.TargetID,
			&i.Category,
			&i.Body,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByStatusCursor = `-- name: ListReportsByStatusCursor :many
SELECT id, reporter_id, target_type, target_id, category, body, status, reviewed_by, reviewed_at, created_at
FROM reports
WHERE status = $1 AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ListReportsByStatusCursorParams struct {
	Status    ReportStatus `json:"status"`
	CreatedAt time.Time    `json:"created_at"`
	Limit     int32        `json:"limit"`
}

func (q *Queries) ListReportsByStatusCursor(ctx context.Context, arg ListReportsByStatusCursorParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByStatusCursor, arg.Status, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.TargetType,
			&i.TargetID,
			&i.Category,
			&i.Body,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports
SET status = $2, reviewed_by = $3, reviewed_at = now()
WHERE id = $1
RETURNING id, reporter_id, target_type, target_id, category, body, status, reviewed_by, reviewed_at, created_at
`

type UpdateReportStatusParams struct {
	ID         uuid.UUID    `json:"id"`
	Status     ReportStatus `json:"status"`
	ReviewedBy pgtype.UUID  `json:"reviewed_by"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus, arg.ID, arg.Status, arg.ReviewedBy)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Category,
		&i.Body,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}
