// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saves.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSave = `-- name: CreateSave :exec
INSERT INTO saves (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT (user_id, course_id) DO NOTHING
`

type CreateSaveParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) CreateSave(ctx context.Context, arg CreateSaveParams) error {
	_, err := q.db.Exec(ctx, createSave, arg.UserID, arg.CourseID)
	return err
}

const deleteSave = `-- name: DeleteSave :exec
DELETE FROM saves WHERE user_id = $1 AND course_id = $2
`

type DeleteSaveParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) DeleteSave(ctx context.Context, arg DeleteSaveParams) error {
	_, err := q.db.Exec(ctx, deleteSave, arg.UserID, arg.CourseID)
	return err
}

const isSaved = `-- name: IsSaved :one
SELECT EXISTS(SELECT 1 FROM saves WHERE user_id = $1 AND course_id = $2) AS is_saved
`

type IsSavedParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
}

func (q *Queries) IsSaved(ctx context.Context, arg IsSavedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSaved, arg.UserID, arg.CourseID)
	var is_saved bool
	err := row.Scan(&is_saved)
	return is_saved, err
}

const listSavedCourses = `-- name: ListSavedCourses :many
SELECT c.id, c.owner_id, c.title, c.description, c.tags, c.thumbnail_url, c.visibility, c.forked_from_id, c.forked_at, c.embed_broken, c.created_at, c.updated_at
FROM saves s
JOIN courses c ON c.id = s.course_id
WHERE s.user_id = $1
ORDER BY s.created_at DESC
`

type ListSavedCoursesRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerID      uuid.UUID          `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Tags         []string           `json:"tags"`
	ThumbnailUrl pgtype.Text        `json:"thumbnail_url"`
	Visibility   Visibility         `json:"visibility"`
	ForkedFromID pgtype.UUID        `json:"forked_from_id"`
	ForkedAt     pgtype.Timestamptz `json:"forked_at"`
	EmbedBroken  bool               `json:"embed_broken"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) ListSavedCourses(ctx context.Context, userID uuid.UUID) ([]ListSavedCoursesRow, error) {
	rows, err := q.db.Query(ctx, listSavedCourses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedCoursesRow
	for rows.Next() {
		var i ListSavedCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.ThumbnailUrl,
			&i.Visibility,
			&i.ForkedFromID,
			&i.ForkedAt,
			&i.EmbedBroken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
