// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelUserDeletion = `-- name: CancelUserDeletion :exec
UPDATE users
SET deletion_scheduled_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) CancelUserDeletion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelUserDeletion, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name)
VALUES ($1, $2)
RETURNING id, email, display_name, bio, avatar_url, is_admin, deleted_at, deletion_scheduled_at, created_at, updated_at
`

type CreateUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.DeletedAt,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePrivateUnlistedCourses = `-- name: DeletePrivateUnlistedCourses :exec
DELETE FROM courses
WHERE owner_id = $1 AND visibility != 'public'
`

func (q *Queries) DeletePrivateUnlistedCourses(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePrivateUnlistedCourses, ownerID)
	return err
}

const deleteUserCompletions = `-- name: DeleteUserCompletions :exec
DELETE FROM completions WHERE user_id = $1
`

func (q *Queries) DeleteUserCompletions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserCompletions, userID)
	return err
}

const deleteUserMagicLinkTokens = `-- name: DeleteUserMagicLinkTokens :exec
DELETE FROM magic_link_tokens WHERE email = (SELECT users.email FROM users WHERE users.id = $1)
`

func (q *Queries) DeleteUserMagicLinkTokens(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserMagicLinkTokens, id)
	return err
}

const deleteUserOAuthAccounts = `-- name: DeleteUserOAuthAccounts :exec
DELETE FROM oauth_accounts WHERE user_id = $1
`

func (q *Queries) DeleteUserOAuthAccounts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserOAuthAccounts, userID)
	return err
}

const deleteUserQuizAttempts = `-- name: DeleteUserQuizAttempts :exec
DELETE FROM quiz_attempts WHERE user_id = $1
`

func (q *Queries) DeleteUserQuizAttempts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserQuizAttempts, userID)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokens, userID)
	return err
}

const deleteUserRelatedData = `-- name: DeleteUserRelatedData :exec
DELETE FROM saves WHERE user_id = $1
`

func (q *Queries) DeleteUserRelatedData(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRelatedData, userID)
	return err
}

const finalizeUserDeletion = `-- name: FinalizeUserDeletion :exec
UPDATE users
SET deleted_at = now(),
    email = 'deleted-' || users.id::text || '@deleted.local',
    display_name = 'Deleted user',
    bio = NULL,
    avatar_url = NULL,
    updated_at = now()
WHERE users.id = $1 AND deletion_scheduled_at IS NOT NULL AND deletion_scheduled_at <= now() AND deleted_at IS NULL
`

func (q *Queries) FinalizeUserDeletion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, finalizeUserDeletion, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, bio, avatar_url, is_admin, deleted_at, deletion_scheduled_at, created_at, updated_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.DeletedAt,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, bio, avatar_url, is_admin, deleted_at, deletion_scheduled_at, created_at, updated_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.DeletedAt,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersWithPendingDeletion = `-- name: GetUsersWithPendingDeletion :many
SELECT id, email, display_name, bio, avatar_url, is_admin, deleted_at, deletion_scheduled_at, created_at, updated_at
FROM users
WHERE deletion_scheduled_at IS NOT NULL AND deletion_scheduled_at <= now() AND deleted_at IS NULL
`

func (q *Queries) GetUsersWithPendingDeletion(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersWithPendingDeletion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.IsAdmin,
			&i.DeletedAt,
			&i.DeletionScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignCoursesToDeletedUser = `-- name: ReassignCoursesToDeletedUser :exec
UPDATE courses
SET owner_id = '00000000-0000-0000-0000-000000000001'
WHERE owner_id = $1 AND visibility = 'public'
`

func (q *Queries) ReassignCoursesToDeletedUser(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, reassignCoursesToDeletedUser, ownerID)
	return err
}

const scheduleUserDeletion = `-- name: ScheduleUserDeletion :exec
UPDATE users
SET deletion_scheduled_at = $2, updated_at = now()
WHERE id = $1
`

type ScheduleUserDeletionParams struct {
	ID                  uuid.UUID          `json:"id"`
	DeletionScheduledAt pgtype.Timestamptz `json:"deletion_scheduled_at"`
}

func (q *Queries) ScheduleUserDeletion(ctx context.Context, arg ScheduleUserDeletionParams) error {
	_, err := q.db.Exec(ctx, scheduleUserDeletion, arg.ID, arg.DeletionScheduledAt)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    bio = COALESCE($3, bio),
    avatar_url = COALESCE($4, avatar_url),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, display_name, bio, avatar_url, is_admin, deleted_at, deletion_scheduled_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.DeletedAt,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
